name: Deploy to Kubernetes

on:
  push:
    branches: [ "main" ]
  workflow_run:
    workflows: [ "Build and Push Docker image" ]  
    types: [ "completed" ]

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy:
    if: ${{ github.event_name == 'push' || (github.event.workflow_run.conclusion == 'success') }}
    runs-on: self-hosted
    labels: [ kubernetes-runner ]
    permissions:
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4

   
      - name: Update Deployment image
        run: |
          kubectl -n pogrom set image deployment/myapp myapp=ghcr.io/${{ github.repository_owner }}/myapp:latest --record

      - name: Wait for rollout
        run: |
          kubectl -n pogrom rollout status deploy/myapp --timeout=180s
